### PR TITLE
Update master with recent mobz

### PR DESCRIPTION
**Pull request by mkostrikin**
Sync mobz/master with Tradeshift fork.
We need this to build debian package of recent head plugin
@sorenmat 
cc: @JesperTerkelsen @tnn

### CODE REVIEW

**Comment by mkostrikin** [comment]
I have no ideas where two comments above are from.

**Comment by sorenmat** [comment]
fine with me :+1:

**Comment by sorenmat** [comment]
Why is it we have our own fork of this again ?

**Comment by mkostrikin** [comment]
Did not get your question.
We want master up-to-date to have less changes at [deb](https://github.com/Tradeshift/elasticsearch-head/tree/deb) branch

**Comment by mkostrikin** [comment]
deb-es2 branch of couse

**Pull request merged**
